# Generated by Django 5.0.5 on 2024-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_remove_userinfo_id_card_remove_userinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='carte_nationale_id',
            field=models.CharField(default='UNKNOWN', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_naissance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
    ]
